-- =============================================================================
-- AUTO-GENERATED by packages/cocktail-seed (src/build-seed.ts).
-- Do not edit by hand — regenerate with: pnpm seed:cocktails:build
-- Generated at: 2026-08-01T00:07:44.892Z
-- Cocktail count: 28
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Official operator user (email-keyed; environment-independent)
-- ---------------------------------------------------------------------------
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
)
SELECT
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'official@sakehub.app',
  crypt('official-seed-only', gen_salt('bf')),
  now(),
  now(),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('display_name', 'SakeHub公式'),
  now(),
  now(),
  '',
  '',
  '',
  ''
WHERE NOT EXISTS (
  SELECT 1 FROM auth.users WHERE email = 'official@sakehub.app'
);

INSERT INTO auth.identities (
  id,
  user_id,
  identity_data,
  provider,
  provider_id,
  last_sign_in_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  u.id,
  jsonb_build_object('sub', u.id::text, 'email', u.email),
  'email',
  u.email,
  now(),
  now(),
  now()
FROM auth.users u
WHERE u.email = 'official@sakehub.app'
  AND NOT EXISTS (
    SELECT 1 FROM auth.identities i
    WHERE i.user_id = u.id AND i.provider = 'email'
  );

UPDATE public.users
SET display_name = 'SakeHub公式'
WHERE email = 'official@sakehub.app';

-- ---------------------------------------------------------------------------
-- cocktails master + official recipes
-- ---------------------------------------------------------------------------

-- aperol-spritz
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'e4662b66-6d38-5874-9541-268d547487a3',
  'aperol-spritz',
  'アペロールスプリッツ',
  'Aperol Spritz',
  'アペロール、プロセッコ、ソーダで作るイタリアの軽快なアペリティーボ。',
  'Liqueur',
  8,
  'Italy'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'e4662b66-6d38-5874-9541-268d547487a3',
  'アペロールスプリッツ（基本レシピ）',
  '比率は 3:2:1（プロセッコ:アペロール:ソーダ）も定番。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24', 'アペロール', 60, 'ml', 0),
  ('1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24', 'プロセッコ', 90, 'ml', 1),
  ('1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24', '炭酸水', 30, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24', 'ワイングラスに氷をたっぷり入れる。', 0),
  ('1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24', 'アペロール、プロセッコ、ソーダを注ぐ。', 1),
  ('1a9eb1d8-f81e-5fd7-892c-4ca51e9f6d24', '軽く混ぜ、オレンジスライスを飾る。', 2);

-- bees-knees
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '6045b947-0e96-5b41-b44a-c95621944ae6',
  'bees-knees',
  'ビーズニーズ',
  'Bee''s Knees',
  'ジン、レモン、はちみつシロップの禁酒法時代生まれのクラシック。はちみつのまろやかさが特徴。',
  'Gin',
  20,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '941089fe-a490-5744-af3c-082a759b5ca4',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '6045b947-0e96-5b41-b44a-c95621944ae6',
  'ビーズニーズ（基本レシピ）',
  'はちみつシロップははちみつと同量の湯で溶いて冷まして使う。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '941089fe-a490-5744-af3c-082a759b5ca4';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '941089fe-a490-5744-af3c-082a759b5ca4';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('941089fe-a490-5744-af3c-082a759b5ca4', 'ドライジン', 50, 'ml', 0),
  ('941089fe-a490-5744-af3c-082a759b5ca4', 'レモン果汁', 22.5, 'ml', 1),
  ('941089fe-a490-5744-af3c-082a759b5ca4', 'はちみつシロップ', 22.5, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('941089fe-a490-5744-af3c-082a759b5ca4', 'シェイカーに材料と氷を入れる。', 0),
  ('941089fe-a490-5744-af3c-082a759b5ca4', 'よくシェイクする。', 1),
  ('941089fe-a490-5744-af3c-082a759b5ca4', 'クーペグラスに注ぐ。', 2);

-- bloody-mary
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'd7085ca7-9276-52bb-b9fb-fe6420b48c32',
  'bloody-mary',
  'ブラッディメアリー',
  'Bloody Mary',
  'ウォッカとトマトジュースをベースにしたスパイシーなロングドリンク。朝食カクテルの定番。',
  'Vodka',
  12,
  'France'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '8c0e59e2-d526-5b88-be45-c3f0b2326084',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'd7085ca7-9276-52bb-b9fb-fe6420b48c32',
  'ブラッディメアリー（基本レシピ）',
  'スパイスは好みで調整する。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '8c0e59e2-d526-5b88-be45-c3f0b2326084';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '8c0e59e2-d526-5b88-be45-c3f0b2326084';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'ウォッカ', 45, 'ml', 0),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'トマトジュース', 90, 'ml', 1),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'レモン果汁', 15, 'ml', 2),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'ウスターソース', 2, 'dash', 3),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'タバスコ', 2, 'dash', 4),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', '塩・こしょう', NULL, NULL, 5);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'ハイボールグラスに氷を入れる。', 0),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', '材料をすべて注ぎ、軽く混ぜる。', 1),
  ('8c0e59e2-d526-5b88-be45-c3f0b2326084', 'セロリやレモンスライスを飾る。', 2);

-- caipirinha
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'a94eb749-8783-537a-9949-6142cb6336de',
  'caipirinha',
  'カイピリーニャ',
  'Caipirinha',
  'カシャッサ、ライム、砂糖で作るブラジルの国民的カクテル。果皮の香りが決め手。',
  'Cachaca',
  20,
  'Brazil'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'd299819a-fca3-5b51-9cf7-6989a4511d4d',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'a94eb749-8783-537a-9949-6142cb6336de',
  'カイピリーニャ（基本レシピ）',
  '白い部分の苦味が強いときは種と白い皮を取り除く。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'd299819a-fca3-5b51-9cf7-6989a4511d4d';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'd299819a-fca3-5b51-9cf7-6989a4511d4d';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('d299819a-fca3-5b51-9cf7-6989a4511d4d', 'カシャッサ', 60, 'ml', 0),
  ('d299819a-fca3-5b51-9cf7-6989a4511d4d', 'ライム', 1, 'piece', 1),
  ('d299819a-fca3-5b51-9cf7-6989a4511d4d', '砂糖', 2, 'tsp', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('d299819a-fca3-5b51-9cf7-6989a4511d4d', 'ライムをくし切りにし、グラスで砂糖と軽く潰す。', 0),
  ('d299819a-fca3-5b51-9cf7-6989a4511d4d', '砕氷を入れる。', 1),
  ('d299819a-fca3-5b51-9cf7-6989a4511d4d', 'カシャッサを注ぎ、軽く混ぜる。', 2);

-- cosmopolitan
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '778eb6aa-6c16-57b6-b322-c84e61fc00f6',
  'cosmopolitan',
  'コスモポリタン',
  'Cosmopolitan',
  'ウォッカ、コアントロー、クランベリー、ライムをシェイクした鮮やかなピンクのモダンクラシック。',
  'Vodka',
  20,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '102cd2c2-16b9-5091-8992-f106e3220db2',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '778eb6aa-6c16-57b6-b322-c84e61fc00f6',
  'コスモポリタン（基本レシピ）',
  NULL,
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '102cd2c2-16b9-5091-8992-f106e3220db2';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '102cd2c2-16b9-5091-8992-f106e3220db2';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'シトラスウォッカ', 40, 'ml', 0),
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'コアントロー', 15, 'ml', 1),
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'クランベリージュース', 30, 'ml', 2),
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'ライム果汁', 10, 'ml', 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'シェイカーに材料と氷を入れる。', 0),
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'よくシェイクする。', 1),
  ('102cd2c2-16b9-5091-8992-f106e3220db2', 'クーペグラスに注ぎ、オレンジピールを飾る。', 2);

-- cuba-libre
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '1c106b40-ba86-5394-870f-8b0dd7cd0c0a',
  'cuba-libre',
  'キューバリブレ',
  'Cuba Libre',
  'ラムとコーラ、ライムで作るシンプルなロングドリンク。自由を願う名を持つキューバの定番。',
  'Rum',
  10,
  'Cuba'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '604f887f-374d-5685-8fe3-ee69758faa78',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '1c106b40-ba86-5394-870f-8b0dd7cd0c0a',
  'キューバリブレ（基本レシピ）',
  NULL,
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '604f887f-374d-5685-8fe3-ee69758faa78';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '604f887f-374d-5685-8fe3-ee69758faa78';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('604f887f-374d-5685-8fe3-ee69758faa78', 'ホワイトラム', 45, 'ml', 0),
  ('604f887f-374d-5685-8fe3-ee69758faa78', 'コーラ', 120, 'ml', 1),
  ('604f887f-374d-5685-8fe3-ee69758faa78', 'ライム果汁', 10, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('604f887f-374d-5685-8fe3-ee69758faa78', 'グラスに氷を入れる。', 0),
  ('604f887f-374d-5685-8fe3-ee69758faa78', 'ラムとライム果汁を注ぐ。', 1),
  ('604f887f-374d-5685-8fe3-ee69758faa78', 'コーラを注ぎ、軽く混ぜる。', 2);

-- daiquiri
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '9da36ee6-d5cc-55e2-9c17-badb0e8d24d0',
  'daiquiri',
  'ダイキリ',
  'Daiquiri',
  'ホワイトラム、ライム、砂糖の三素材で構成されるキューバの名作。シンプルゆえにバランスが命。',
  'Rum',
  22,
  'Cuba'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'd03f7b55-7490-5369-96b1-39260a3175e5',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '9da36ee6-d5cc-55e2-9c17-badb0e8d24d0',
  'ダイキリ（基本レシピ）',
  '甘酸っぱさのバランスを好みで微調整する。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'd03f7b55-7490-5369-96b1-39260a3175e5';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'd03f7b55-7490-5369-96b1-39260a3175e5';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('d03f7b55-7490-5369-96b1-39260a3175e5', 'ホワイトラム', 45, 'ml', 0),
  ('d03f7b55-7490-5369-96b1-39260a3175e5', 'ライム果汁', 22.5, 'ml', 1),
  ('d03f7b55-7490-5369-96b1-39260a3175e5', 'シュガーシロップ', 15, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('d03f7b55-7490-5369-96b1-39260a3175e5', 'シェイカーに材料と氷を入れる。', 0),
  ('d03f7b55-7490-5369-96b1-39260a3175e5', 'しっかりシェイクする。', 1),
  ('d03f7b55-7490-5369-96b1-39260a3175e5', 'クーペグラスに注ぐ。', 2);

-- dry-martini
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'e23aa9eb-7fac-5b55-a09c-3983c6c8d948',
  'dry-martini',
  'ドライマティーニ',
  'Dry Martini',
  'ジンとドライベルモットをステアしたカクテルの王様。比率とステアの加減で個性が出る。',
  'Gin',
  30,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '38dd5c32-8f8f-52c3-aa65-2a6c39f66abf',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'e23aa9eb-7fac-5b55-a09c-3983c6c8d948',
  'ドライマティーニ（基本レシピ）',
  'グラスはあらかじめ冷やしておく。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '38dd5c32-8f8f-52c3-aa65-2a6c39f66abf';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '38dd5c32-8f8f-52c3-aa65-2a6c39f66abf';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('38dd5c32-8f8f-52c3-aa65-2a6c39f66abf', 'ドライジン', 60, 'ml', 0),
  ('38dd5c32-8f8f-52c3-aa65-2a6c39f66abf', 'ドライベルモット', 10, 'ml', 1);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('38dd5c32-8f8f-52c3-aa65-2a6c39f66abf', 'ミキシンググラスに氷と材料を入れる。', 0),
  ('38dd5c32-8f8f-52c3-aa65-2a6c39f66abf', '静かにステアして冷やす。', 1),
  ('38dd5c32-8f8f-52c3-aa65-2a6c39f66abf', '冷やしたカクテルグラスに注ぎ、オリーブまたはレモンピールを飾る。', 2);

-- espresso-martini
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c153ab11-335f-5956-8a51-28efcc35b7a5',
  'espresso-martini',
  'エスプレッソマティーニ',
  'Espresso Martini',
  'ウォッカ、コーヒーリキュール、エスプレッソをシェイクしたモダンクラシック。クレマが魅力。',
  'Vodka',
  18,
  'United Kingdom'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '591ce14e-0187-5ea6-b949-be47d7d29ffc',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c153ab11-335f-5956-8a51-28efcc35b7a5',
  'エスプレッソマティーニ（基本レシピ）',
  'エスプレッソは抽出したてを少し冷まして使う。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '591ce14e-0187-5ea6-b949-be47d7d29ffc';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '591ce14e-0187-5ea6-b949-be47d7d29ffc';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', 'ウォッカ', 45, 'ml', 0),
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', 'コーヒーリキュール', 20, 'ml', 1),
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', 'エスプレッソ', 30, 'ml', 2),
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', 'シュガーシロップ', 10, 'ml', 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', 'シェイカーに材料と氷を入れる。', 0),
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', '強くシェイクしてクレマを立てる。', 1),
  ('591ce14e-0187-5ea6-b949-be47d7d29ffc', 'クーペに注ぎ、コーヒー豆を飾る。', 2);

-- french-75
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '9f644106-3400-5e46-92d4-09df7a190907',
  'french-75',
  'フレンチ75',
  'French 75',
  'ジン、レモン、シロップにシャンパンを注ぐ華やかな発泡系クラシック。',
  'Gin',
  15,
  'France'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'dce5cd96-64fd-577b-b285-9d7a867f7a83',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '9f644106-3400-5e46-92d4-09df7a190907',
  'フレンチ75（基本レシピ）',
  'シャンパンは最後に注ぎ、泡を潰さない。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'dce5cd96-64fd-577b-b285-9d7a867f7a83';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'dce5cd96-64fd-577b-b285-9d7a867f7a83';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'ドライジン', 30, 'ml', 0),
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'レモン果汁', 15, 'ml', 1),
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'シュガーシロップ', 10, 'ml', 2),
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'シャンパン', 60, 'ml', 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'シェイカーでジン、レモン、シロップをシェイクする。', 0),
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'フルートグラスに注ぐ。', 1),
  ('dce5cd96-64fd-577b-b285-9d7a867f7a83', 'シャンパンを静かに加えて飾る。', 2);

-- gin-tonic
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000004',
  'gin-tonic',
  'ジントニック',
  'Gin and Tonic',
  'ジンをトニックウォーターで割るだけのシンプルカクテル。ジンのボタニカルとトニックの苦味が織りなす永遠の定番。',
  'Gin',
  8,
  'United Kingdom'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'f8ce6b98-5ab5-5700-b16d-fe619c87be11',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000004',
  'ジントニック（基本レシピ）',
  '氷はたっぷり、炭酸は最後に静かに注ぐ。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'f8ce6b98-5ab5-5700-b16d-fe619c87be11';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'f8ce6b98-5ab5-5700-b16d-fe619c87be11';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('f8ce6b98-5ab5-5700-b16d-fe619c87be11', 'ドライジン', 45, 'ml', 0),
  ('f8ce6b98-5ab5-5700-b16d-fe619c87be11', 'トニックウォーター', 135, 'ml', 1),
  ('f8ce6b98-5ab5-5700-b16d-fe619c87be11', 'ライム', 0.25, 'piece', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('f8ce6b98-5ab5-5700-b16d-fe619c87be11', 'ハイボールグラスに氷をたっぷり入れる。', 0),
  ('f8ce6b98-5ab5-5700-b16d-fe619c87be11', 'ジンを注ぐ。', 1),
  ('f8ce6b98-5ab5-5700-b16d-fe619c87be11', 'トニックウォーターを静かに注ぎ、ライムを絞って落とす。', 2);

-- highball
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000008',
  'highball',
  'ハイボール',
  'Highball',
  'ウイスキーをソーダで割った軽快なロングドリンク。食中酒の定番として日本で絶大な人気を誇る。',
  'Whisky',
  7,
  'Japan'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '4ec3974e-0815-5a4c-b192-38702d42d061',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000008',
  'ハイボール（基本レシピ）',
  '混ぜるのは縦に1回だけ。炭酸を潰さない。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '4ec3974e-0815-5a4c-b192-38702d42d061';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '4ec3974e-0815-5a4c-b192-38702d42d061';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('4ec3974e-0815-5a4c-b192-38702d42d061', 'ウイスキー', 30, 'ml', 0),
  ('4ec3974e-0815-5a4c-b192-38702d42d061', '炭酸水', 120, 'ml', 1);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('4ec3974e-0815-5a4c-b192-38702d42d061', 'ハイボールグラスに氷をたっぷり入れる。', 0),
  ('4ec3974e-0815-5a4c-b192-38702d42d061', 'ウイスキーを注ぐ。', 1),
  ('4ec3974e-0815-5a4c-b192-38702d42d061', '炭酸水を注ぎ、マドラーで縦に一度だけステアする。', 2);

-- lemon-sour
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000001',
  'lemon-sour',
  'レモンサワー',
  'Lemon Sour',
  '焼酎やウォッカをベースにレモン果汁と炭酸で割った日本の居酒屋定番カクテル。すっきり爽快で食事にも合う。',
  'Shochu',
  5,
  'Japan'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '8c5a9c47-2a33-5d0b-acff-9c44b46185ce',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000001',
  'レモンサワー（基本レシピ）',
  '氷はたっぷり入れ、炭酸は最後に静かに注ぐ。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '8c5a9c47-2a33-5d0b-acff-9c44b46185ce';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '8c5a9c47-2a33-5d0b-acff-9c44b46185ce';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('8c5a9c47-2a33-5d0b-acff-9c44b46185ce', '甲類焼酎', 45, 'ml', 0),
  ('8c5a9c47-2a33-5d0b-acff-9c44b46185ce', 'レモン果汁', 20, 'ml', 1),
  ('8c5a9c47-2a33-5d0b-acff-9c44b46185ce', '炭酸水', 120, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('8c5a9c47-2a33-5d0b-acff-9c44b46185ce', 'グラスに氷をたっぷり入れる。', 0),
  ('8c5a9c47-2a33-5d0b-acff-9c44b46185ce', '甲類焼酎とレモン果汁を注ぎ、軽く混ぜる。', 1),
  ('8c5a9c47-2a33-5d0b-acff-9c44b46185ce', '炭酸水を静かに注ぎ、縦に一度だけステアする。', 2);

-- long-island-iced-tea
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'b52cc965-e893-591b-a1e6-9b1ee3fac577',
  'long-island-iced-tea',
  'ロングアイランドアイスティー',
  'Long Island Iced Tea',
  '複数のスピリッツにレモンとコーラを合わせた強度のあるアメリカンカクテル。見た目はアイスティーに近い。',
  'Vodka',
  22,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '438f1465-c2ee-5e2f-afbd-ab567c0014d1',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'b52cc965-e893-591b-a1e6-9b1ee3fac577',
  'ロングアイランドアイスティー（基本レシピ）',
  'スピリッツが多いので飲み過ぎに注意。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '438f1465-c2ee-5e2f-afbd-ab567c0014d1';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '438f1465-c2ee-5e2f-afbd-ab567c0014d1';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'ウォッカ', 15, 'ml', 0),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'ドライジン', 15, 'ml', 1),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'ホワイトラム', 15, 'ml', 2),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'テキーラ', 15, 'ml', 3),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'ホワイトキュラソー', 15, 'ml', 4),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'レモン果汁', 25, 'ml', 5),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'シュガーシロップ', 20, 'ml', 6),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'コーラ', 30, 'ml', 7);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'シェイカーにコーラ以外の材料と氷を入れてシェイクする。', 0),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', '氷入りグラスに注ぐ。', 1),
  ('438f1465-c2ee-5e2f-afbd-ab567c0014d1', 'コーラを静かに注いで仕上げる。', 2);

-- mai-tai
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '7168f33f-d07f-5edc-a0ab-4dd4b19f72f8',
  'mai-tai',
  'マイタイ',
  'Mai Tai',
  'ラムを主体にオレンジリキュールとライム、オルジェアで仕上げるトロピカルクラシック。',
  'Rum',
  22,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'f89db70a-d952-5400-b7b0-b5bd77a3d839',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '7168f33f-d07f-5edc-a0ab-4dd4b19f72f8',
  'マイタイ（基本レシピ）',
  'フロートでダークラムを浮かせてもよい。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'f89db70a-d952-5400-b7b0-b5bd77a3d839';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'f89db70a-d952-5400-b7b0-b5bd77a3d839';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'ホワイトラム', 30, 'ml', 0),
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'ダークラム', 30, 'ml', 1),
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'オレンジキュラソー', 15, 'ml', 2),
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'ライム果汁', 20, 'ml', 3),
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'オルジェアシロップ', 10, 'ml', 4);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'シェイカーに氷と材料を入れる。', 0),
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'シェイクしてロックグラスに注ぐ。', 1),
  ('f89db70a-d952-5400-b7b0-b5bd77a3d839', 'ミントとライムを飾る。', 2);

-- manhattan
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000002',
  'manhattan',
  'マンハッタン',
  'Manhattan',
  'ウイスキーとスイートベルモットをステアした「カクテルの女王」。芳醇で気品ある甘みとビターズの香りが特徴。',
  'Whisky',
  30,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'e887cd2f-356d-5cf0-8ce3-32abdbba5a84',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000002',
  'マンハッタン（基本レシピ）',
  'ステアは静かに丁寧に。チェリーはマラスキーノを添える。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'e887cd2f-356d-5cf0-8ce3-32abdbba5a84';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'e887cd2f-356d-5cf0-8ce3-32abdbba5a84';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', 'ライウイスキー', 45, 'ml', 0),
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', 'スイートベルモット', 15, 'ml', 1),
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', 'アンゴスチュラビターズ', 1, 'dash', 2),
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', 'マラスキーノチェリー', 1, 'piece', 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', 'ミキシンググラスに氷を入れ、材料を注ぐ。', 0),
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', '静かにステアして冷やす。', 1),
  ('e887cd2f-356d-5cf0-8ce3-32abdbba5a84', 'カクテルグラスに注ぎ、チェリーを飾る。', 2);

-- margarita
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000007',
  'margarita',
  'マルガリータ',
  'Margarita',
  'テキーラ、ホワイトキュラソー、ライムをシェイクし、塩でスノースタイルにしたメキシコ生まれの世界的カクテル。',
  'Tequila',
  25,
  'Mexico'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'ba120aaf-9e98-5fd5-a20b-6e3fd5e62948',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000007',
  'マルガリータ（基本レシピ）',
  'グラスの縁に塩を付けるスノースタイルで。シェイクは強めに。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'ba120aaf-9e98-5fd5-a20b-6e3fd5e62948';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'ba120aaf-9e98-5fd5-a20b-6e3fd5e62948';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', 'テキーラ', 45, 'ml', 0),
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', 'ホワイトキュラソー', 20, 'ml', 1),
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', 'ライム果汁', 15, 'ml', 2),
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', '塩', NULL, NULL, 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', 'クーペグラスの縁をライムで湿らせ、塩を付ける。', 0),
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', 'シェイカーに氷と材料を入れ、強くシェイクする。', 1),
  ('ba120aaf-9e98-5fd5-a20b-6e3fd5e62948', 'グラスに注ぐ。', 2);

-- mint-julep
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '42b040f0-a9aa-51f7-8ae0-26f6bfe614db',
  'mint-julep',
  'ミントジュレップ',
  'Mint Julep',
  'バーボン、ミント、砂糖を砕氷で仕上げるケンタッキーダービーの公式ドリンク。',
  'Whisky',
  25,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'f379887f-5882-5650-8976-b4d801d9fda4',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '42b040f0-a9aa-51f7-8ae0-26f6bfe614db',
  'ミントジュレップ（基本レシピ）',
  'ミントは叩きすぎず香りだけを立たせる。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'f379887f-5882-5650-8976-b4d801d9fda4';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'f379887f-5882-5650-8976-b4d801d9fda4';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('f379887f-5882-5650-8976-b4d801d9fda4', 'バーボンウイスキー', 60, 'ml', 0),
  ('f379887f-5882-5650-8976-b4d801d9fda4', 'ミントの葉', 10, 'piece', 1),
  ('f379887f-5882-5650-8976-b4d801d9fda4', 'シュガーシロップ', 15, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('f379887f-5882-5650-8976-b4d801d9fda4', 'グラスでミントとシロップを軽く押す。', 0),
  ('f379887f-5882-5650-8976-b4d801d9fda4', '砕氷を高く盛り、バーボンを注ぐ。', 1),
  ('f379887f-5882-5650-8976-b4d801d9fda4', '軽く混ぜ、ミントの穂を飾る。', 2);

-- mojito
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000003',
  'mojito',
  'モヒート',
  'Mojito',
  'ホワイトラム、ライム、ミント、砂糖、ソーダで作るキューバ生まれの定番カクテル。爽やかで飲みやすい夏の一杯。',
  'Rum',
  10,
  'Cuba'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '1a225b91-39fc-5c49-bb47-7b849ed3b1e2',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000003',
  'モヒート（基本レシピ）',
  'ミントは潰しすぎず香りを立たせる。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '1a225b91-39fc-5c49-bb47-7b849ed3b1e2';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '1a225b91-39fc-5c49-bb47-7b849ed3b1e2';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', 'ホワイトラム', 45, 'ml', 0),
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', 'ライム果汁', 20, 'ml', 1),
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', '砂糖', 2, 'tsp', 2),
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', 'ミントの葉', 10, 'piece', 3),
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', '炭酸水', 60, 'ml', 4);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', 'グラスにミント、砂糖、ライム果汁を入れ、軽くマドラーで押す。', 0),
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', '砕氷を入れ、ホワイトラムを注ぐ。', 1),
  ('1a225b91-39fc-5c49-bb47-7b849ed3b1e2', '炭酸水を加えて軽く混ぜ、ミントを飾る。', 2);

-- moscow-mule
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '98343bf2-c6eb-5fb0-b188-98c41e062ea8',
  'moscow-mule',
  'モスコミュール',
  'Moscow Mule',
  'ウォッカ、ジンジャービア、ライムで作るアメリカ発のモダンクラシック。銅マグで出すスタイルが象徴的。',
  'Vodka',
  12,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'f696662f-9e81-53e2-80de-90f6425d144e',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '98343bf2-c6eb-5fb0-b188-98c41e062ea8',
  'モスコミュール（基本レシピ）',
  'ジンジャービアはよく冷やしたものを使う。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'f696662f-9e81-53e2-80de-90f6425d144e';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'f696662f-9e81-53e2-80de-90f6425d144e';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('f696662f-9e81-53e2-80de-90f6425d144e', 'ウォッカ', 45, 'ml', 0),
  ('f696662f-9e81-53e2-80de-90f6425d144e', 'ライム果汁', 15, 'ml', 1),
  ('f696662f-9e81-53e2-80de-90f6425d144e', 'ジンジャービア', 120, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('f696662f-9e81-53e2-80de-90f6425d144e', '銅マグまたはグラスに氷を入れる。', 0),
  ('f696662f-9e81-53e2-80de-90f6425d144e', 'ウォッカとライム果汁を注ぐ。', 1),
  ('f696662f-9e81-53e2-80de-90f6425d144e', 'ジンジャービアを注ぎ、軽く混ぜてライムを飾る。', 2);

-- negroni
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000005',
  'negroni',
  'ネグローニ',
  'Negroni',
  'ジン、カンパリ、スイートベルモットを等量で割るイタリアの名作カクテル。ほろ苦くビターな味わいが通好み。',
  'Gin',
  24,
  'Italy'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '037c40e2-f683-5c3e-b431-ea02d30be946',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000005',
  'ネグローニ（基本レシピ）',
  'オレンジピールをねじって香りを纏わせる。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '037c40e2-f683-5c3e-b431-ea02d30be946';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '037c40e2-f683-5c3e-b431-ea02d30be946';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('037c40e2-f683-5c3e-b431-ea02d30be946', 'ドライジン', 30, 'ml', 0),
  ('037c40e2-f683-5c3e-b431-ea02d30be946', 'カンパリ', 30, 'ml', 1),
  ('037c40e2-f683-5c3e-b431-ea02d30be946', 'スイートベルモット', 30, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('037c40e2-f683-5c3e-b431-ea02d30be946', 'ロックグラスに大きな氷を入れる。', 0),
  ('037c40e2-f683-5c3e-b431-ea02d30be946', 'ジン、カンパリ、スイートベルモットを等量注ぐ。', 1),
  ('037c40e2-f683-5c3e-b431-ea02d30be946', '軽くステアし、オレンジピールを飾る。', 2);

-- old-fashioned
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'c0c00000-0000-4000-8000-000000000006',
  'old-fashioned',
  'オールドファッションド',
  'Old Fashioned',
  'バーボンまたはライウイスキーに角砂糖とビターズを加えた、カクテルの原点。シンプルだが奥深い大人の味わい。',
  'Whisky',
  32,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '8004c29b-06f2-53f9-9f9c-d6f739535c9c',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'c0c00000-0000-4000-8000-000000000006',
  'オールドファッションド（基本レシピ）',
  '角砂糖にビターズを染み込ませてから潰すのが本式。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '8004c29b-06f2-53f9-9f9c-d6f739535c9c';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '8004c29b-06f2-53f9-9f9c-d6f739535c9c';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', 'バーボンウイスキー', 45, 'ml', 0),
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', '角砂糖', 1, 'piece', 1),
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', 'アンゴスチュラビターズ', 2, 'dash', 2),
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', '水', 5, 'ml', 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', 'グラスに角砂糖とビターズ、少量の水を入れ、マドラーで溶かす。', 0),
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', '大きな氷を入れ、バーボンを注ぐ。', 1),
  ('8004c29b-06f2-53f9-9f9c-d6f739535c9c', '軽くステアし、オレンジピールを飾る。', 2);

-- paloma
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '60d16e45-0525-5378-9143-96dad496fb66',
  'paloma',
  'パロマ',
  'Paloma',
  'テキーラとグレープフルーツソーダの爽やかなロングドリンク。メキシコでマルガリータ以上に親しまれる。',
  'Tequila',
  12,
  'Mexico'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '385091da-42aa-5eed-a518-8825b5a91165',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '60d16e45-0525-5378-9143-96dad496fb66',
  'パロマ（基本レシピ）',
  NULL,
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '385091da-42aa-5eed-a518-8825b5a91165';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '385091da-42aa-5eed-a518-8825b5a91165';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('385091da-42aa-5eed-a518-8825b5a91165', 'テキーラ', 45, 'ml', 0),
  ('385091da-42aa-5eed-a518-8825b5a91165', 'ライム果汁', 15, 'ml', 1),
  ('385091da-42aa-5eed-a518-8825b5a91165', 'グレープフルーツソーダ', 120, 'ml', 2),
  ('385091da-42aa-5eed-a518-8825b5a91165', '塩', NULL, NULL, 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('385091da-42aa-5eed-a518-8825b5a91165', 'グラスの縁に塩を付け、氷を入れる。', 0),
  ('385091da-42aa-5eed-a518-8825b5a91165', 'テキーラとライム果汁を注ぐ。', 1),
  ('385091da-42aa-5eed-a518-8825b5a91165', 'グレープフルーツソーダを注ぎ、軽く混ぜる。', 2);

-- pina-colada
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'e07fecbf-d666-5734-832f-000d545eb16d',
  'pina-colada',
  'ピニャコラーダ',
  'Piña Colada',
  'ラム、パイナップル、ココナッツミルクのトロピカルカクテル。プエルトリコ発祥の国民的一杯。',
  'Rum',
  13,
  'Puerto Rico'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'c06385cf-48b8-5087-8813-b4c7c186b3fa',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'e07fecbf-d666-5734-832f-000d545eb16d',
  'ピニャコラーダ（基本レシピ）',
  'フローズンにする場合はクラッシュアイスを多めに。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'c06385cf-48b8-5087-8813-b4c7c186b3fa';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'c06385cf-48b8-5087-8813-b4c7c186b3fa';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('c06385cf-48b8-5087-8813-b4c7c186b3fa', 'ホワイトラム', 45, 'ml', 0),
  ('c06385cf-48b8-5087-8813-b4c7c186b3fa', 'ココナッツクリーム', 30, 'ml', 1),
  ('c06385cf-48b8-5087-8813-b4c7c186b3fa', 'パイナップルジュース', 90, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('c06385cf-48b8-5087-8813-b4c7c186b3fa', 'ブレンダーまたはシェイカーに材料と氷を入れる。', 0),
  ('c06385cf-48b8-5087-8813-b4c7c186b3fa', '滑らかになるまで混ぜる。', 1),
  ('c06385cf-48b8-5087-8813-b4c7c186b3fa', 'グラスに注ぎ、パイナップルを飾る。', 2);

-- sidecar
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'b04b065e-7d24-5558-88ff-87771b4a40f3',
  'sidecar',
  'サイドカー',
  'Sidecar',
  'コニャック、オレンジリキュール、レモン果汁をシェイクしたエレガントなサワー系クラシック。',
  'Brandy',
  25,
  'France'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '87e3ef28-e7c5-573d-9143-986f99895f1e',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'b04b065e-7d24-5558-88ff-87771b4a40f3',
  'サイドカー（基本レシピ）',
  '好みでグラスの縁にシュガーリムを付けてもよい。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '87e3ef28-e7c5-573d-9143-986f99895f1e';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '87e3ef28-e7c5-573d-9143-986f99895f1e';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('87e3ef28-e7c5-573d-9143-986f99895f1e', 'コニャック', 45, 'ml', 0),
  ('87e3ef28-e7c5-573d-9143-986f99895f1e', 'ホワイトキュラソー', 20, 'ml', 1),
  ('87e3ef28-e7c5-573d-9143-986f99895f1e', 'レモン果汁', 20, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('87e3ef28-e7c5-573d-9143-986f99895f1e', 'シェイカーに材料と氷を入れる。', 0),
  ('87e3ef28-e7c5-573d-9143-986f99895f1e', 'よくシェイクする。', 1),
  ('87e3ef28-e7c5-573d-9143-986f99895f1e', 'クーペグラスに注ぐ。', 2);

-- singapore-sling
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '0c8d9c8e-86cc-5853-b55e-2e8c7cfef6c0',
  'singapore-sling',
  'シンガポールスリング',
  'Singapore Sling',
  'ジンをベースにリキュールと果汁を重ねた華やかなロングドリンク。ラッフルズホテル発祥。',
  'Gin',
  15,
  'Singapore'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  '0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '0c8d9c8e-86cc-5853-b55e-2e8c7cfef6c0',
  'シンガポールスリング（基本レシピ）',
  NULL,
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = '0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = '0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'ドライジン', 30, 'ml', 0),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'チェリーブランデー', 15, 'ml', 1),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'コアントロー', 7.5, 'ml', 2),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'ベネディクティン', 7.5, 'ml', 3),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'パイナップルジュース', 120, 'ml', 4),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'ライム果汁', 15, 'ml', 5),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'グレナデン', 10, 'ml', 6),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'アンゴスチュラビターズ', 1, 'dash', 7);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'シェイカーに材料と氷を入れる。', 0),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', 'よくシェイクする。', 1),
  ('0fcd8bf6-18fe-5a98-84ab-8005d18ef6ec', '氷入りのハイボールグラスに注ぎ、飾りを添える。', 2);

-- tom-collins
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  '9d0c5d52-08b2-582a-9433-a0daf10ab766',
  'tom-collins',
  'トムコリンズ',
  'Tom Collins',
  'ジン、レモン、砂糖、ソーダの爽やかなロングドリンク。コリンズグラスで出す古典。',
  'Gin',
  12,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'ad122c74-1c6f-523c-982e-76a742e88f31',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  '9d0c5d52-08b2-582a-9433-a0daf10ab766',
  'トムコリンズ（基本レシピ）',
  NULL,
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'ad122c74-1c6f-523c-982e-76a742e88f31';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'ad122c74-1c6f-523c-982e-76a742e88f31';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('ad122c74-1c6f-523c-982e-76a742e88f31', 'ドライジン', 45, 'ml', 0),
  ('ad122c74-1c6f-523c-982e-76a742e88f31', 'レモン果汁', 22.5, 'ml', 1),
  ('ad122c74-1c6f-523c-982e-76a742e88f31', 'シュガーシロップ', 15, 'ml', 2),
  ('ad122c74-1c6f-523c-982e-76a742e88f31', '炭酸水', 60, 'ml', 3);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('ad122c74-1c6f-523c-982e-76a742e88f31', 'シェイカーでジン、レモン、シロップをシェイクする。', 0),
  ('ad122c74-1c6f-523c-982e-76a742e88f31', '氷入りのコリンズグラスに注ぐ。', 1),
  ('ad122c74-1c6f-523c-982e-76a742e88f31', '炭酸水を加えて軽く混ぜる。', 2);

-- whiskey-sour
INSERT INTO cocktails (id, slug, name, name_en, description, base_spirit, abv, origin_country)
VALUES (
  'b1c0aba9-b2cd-5aee-95d8-d47aafd1605f',
  'whiskey-sour',
  'ウイスキーサワー',
  'Whiskey Sour',
  'ウイスキー、レモン果汁、シロップをシェイクした古典的サワー。卵白を加えるバリエーションも人気。',
  'Whisky',
  20,
  'United States'
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  description = EXCLUDED.description,
  base_spirit = EXCLUDED.base_spirit,
  abv = EXCLUDED.abv,
  origin_country = EXCLUDED.origin_country,
  updated_at = now();

INSERT INTO cocktail_recipes (id, user_id, cocktail_id, name, memo, status, is_official)
VALUES (
  'c9d28594-43a7-5b6c-973f-fe24750557c0',
  (SELECT id FROM auth.users WHERE email = 'official@sakehub.app'),
  'b1c0aba9-b2cd-5aee-95d8-d47aafd1605f',
  'ウイスキーサワー（基本レシピ）',
  '好みで卵白を加えてドライシェイクすると泡立ちが美しい。',
  'published',
  true
)
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  cocktail_id = EXCLUDED.cocktail_id,
  name = EXCLUDED.name,
  memo = EXCLUDED.memo,
  status = EXCLUDED.status,
  is_official = EXCLUDED.is_official,
  updated_at = now();

DELETE FROM cocktail_recipe_ingredients WHERE recipe_id = 'c9d28594-43a7-5b6c-973f-fe24750557c0';
DELETE FROM cocktail_recipe_steps WHERE recipe_id = 'c9d28594-43a7-5b6c-973f-fe24750557c0';

INSERT INTO cocktail_recipe_ingredients (recipe_id, name, amount, unit, sort_order) VALUES
  ('c9d28594-43a7-5b6c-973f-fe24750557c0', 'バーボンウイスキー', 45, 'ml', 0),
  ('c9d28594-43a7-5b6c-973f-fe24750557c0', 'レモン果汁', 22.5, 'ml', 1),
  ('c9d28594-43a7-5b6c-973f-fe24750557c0', 'シュガーシロップ', 15, 'ml', 2);

INSERT INTO cocktail_recipe_steps (recipe_id, body, sort_order) VALUES
  ('c9d28594-43a7-5b6c-973f-fe24750557c0', 'シェイカーに材料と氷を入れる。', 0),
  ('c9d28594-43a7-5b6c-973f-fe24750557c0', 'よくシェイクして冷やす。', 1),
  ('c9d28594-43a7-5b6c-973f-fe24750557c0', 'ロックグラスまたはクーペに注ぐ。', 2);

